{
	"version": 1695789260,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/backgroundutama-sheet0.png",
		"images/lagudaerahjawatimur-sheet0.png",
		"images/tombolmateri-sheet0.png",
		"images/tombolmateri-sheet1.png",
		"images/karakterjawa-sheet0.png",
		"images/karaktermadura-sheet0.png",
		"images/layoutopening-sheet0.png",
		"images/bumperpembatik-sheet0.png",
		"images/bumperpembatik-sheet1.png",
		"images/bumperpembatik-sheet2.png",
		"images/bumperpembatik-sheet3.png",
		"images/bumperpembatik-sheet4.png",
		"images/bumperpembatik-sheet5.png",
		"images/bumperpembatik-sheet6.png",
		"images/bumperpembatik-sheet7.png",
		"images/bumperpembatik-sheet8.png",
		"images/bumperpembatik-sheet9.png",
		"images/bumperpembatik-sheet10.png",
		"images/layoutpendahuluan-sheet0.png",
		"images/layoutmateri-sheet0.png",
		"images/layoutprofil-sheet0.png",
		"images/layoutreferensi-sheet0.png",
		"images/tbexit-sheet0.png",
		"images/tbexit-sheet1.png",
		"images/tblpendahuluan-sheet0.png",
		"images/tblmateri-sheet0.png",
		"images/tblprofil-sheet0.png",
		"images/tblreferensi-sheet0.png",
		"images/tblquiz-sheet0.png",
		"images/soal-sheet0.png",
		"images/soal2-sheet0.png",
		"images/soal3-sheet0.png",
		"images/soal4-sheet0.png",
		"images/soal5-sheet0.png",
		"images/1a-sheet0.png",
		"images/bgpembatikbumper-sheet0.png",
		"images/logogcc-sheet0.png",
		"media/click.m4a",
		"media/click.ogg",
		"media/rekayorek.m4a",
		"media/rekayorek.ogg",
		"media/bumper.m4a",
		"media/bumper.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"luk luk umbu.mp4",
		"ulan andung andung.mp4",
		"rek ayo rek.mp4",
		"tanduk majeng.mp4",
		"kembang melate.mp4",
		"bumper pembatik.mp4"
	]
}